version: '3'

services:
  softether:
    image: softethervpn/vpnserver:stable
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - 553:53
      - 8443:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "softether_vpn_vol_data:/mnt"
      - "softether_vpn_vol_log:/root/server_log"
      - "softether_vpn_vol_packetlog:/root/packet_log"
      - "softether_vpn_vol_securitylog:/root/security_log"

volumes:
  softether_vpn_vol_data:
  softether_vpn_vol_log:
  softether_vpn_vol_packetlog:
  softether_vpn_vol_securitylog:
